// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WordGenerator.Api.Infra.Context;

#nullable disable

namespace WordGenerator.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260620162701_AddContentElements")]
    partial class AddContentElements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.ContentElement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CoverPageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ImageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MasterSectionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("ParagraphText")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<long?>("SubSectionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TableId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TemplateSectionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoverPageId");

                    b.HasIndex("ImageId");

                    b.HasIndex("MasterSectionId");

                    b.HasIndex("Order");

                    b.HasIndex("SubSectionId");

                    b.HasIndex("TableId");

                    b.HasIndex("TemplateSectionId");

                    b.HasIndex("CoverPageId", "Order");

                    b.HasIndex("MasterSectionId", "Order");

                    b.HasIndex("SubSectionId", "Order");

                    b.HasIndex("TemplateSectionId", "Order");

                    b.ToTable("ContentElements", (string)null);
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.CoverPageItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CoverPageTemplateId")
                        .HasColumnType("bigint");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CoverPageTemplateId");

                    b.ToTable("CoverPageItems");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.CoverPageTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DocumentTemplateId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTemplateId")
                        .IsUnique();

                    b.ToTable("CoverPageTemplates", (string)null);
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.DocumentTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("DocumentTemplates", (string)null);
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.DynamicTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CoverPageTemplateId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MasterSectionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("RowNumberHeader")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ShowRowNumbers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long?>("SubSectionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TemplateSectionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CoverPageTemplateId");

                    b.HasIndex("MasterSectionId");

                    b.HasIndex("Order");

                    b.HasIndex("SubSectionId");

                    b.HasIndex("TemplateSectionId");

                    b.ToTable("DynamicTables", (string)null);
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.ImageGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CoverPageId")
                        .HasColumnType("bigint");

                    b.Property<int>("ImagesPerRow")
                        .HasColumnType("int");

                    b.Property<long?>("MasterSectionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<long?>("SubSectionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TemplateSectionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CoverPageId");

                    b.HasIndex("MasterSectionId");

                    b.HasIndex("SubSectionId");

                    b.HasIndex("TemplateSectionId");

                    b.ToTable("ImageGroup");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.ImageItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Caption")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long?>("CoverPageId")
                        .HasColumnType("bigint");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("Height")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<long?>("ImageGroupId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MasterSectionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<long?>("SubSectionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TemplateSectionId")
                        .HasColumnType("bigint");

                    b.Property<double>("Width")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(500.0);

                    b.HasKey("Id");

                    b.HasIndex("CoverPageId");

                    b.HasIndex("ImageGroupId");

                    b.HasIndex("MasterSectionId");

                    b.HasIndex("Order");

                    b.HasIndex("SubSectionId");

                    b.HasIndex("TemplateSectionId");

                    b.ToTable("Images", (string)null);
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.MasterSection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<bool>("ShowInToc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Order");

                    b.HasIndex("TemplateId", "Order");

                    b.ToTable("MasterSections", (string)null);
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.SubSection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("MasterSectionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<bool>("ShowInToc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Order");

                    b.HasIndex("MasterSectionId", "Order");

                    b.ToTable("SubSections", (string)null);
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.TableColumnDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DynamicTableId")
                        .HasColumnType("bigint");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsRowNumberColumn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Order");

                    b.HasIndex("DynamicTableId", "Order");

                    b.ToTable("TableColumns", (string)null);
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.TableDataCell", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("TableColumnDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<long>("TableDataRowId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("TableColumnDefinitionId");

                    b.HasIndex("TableDataRowId", "TableColumnDefinitionId")
                        .IsUnique();

                    b.ToTable("TableCells", (string)null);
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.TableDataRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DynamicTableId")
                        .HasColumnType("bigint");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DynamicTableId", "RowNumber");

                    b.ToTable("TableRows", (string)null);
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.TemplateSection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Order");

                    b.HasIndex("TemplateId", "Order");

                    b.ToTable("TemplateSections", (string)null);
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.ContentElement", b =>
                {
                    b.HasOne("WordGenerator.Api.Domain.Entities.CoverPageTemplate", "CoverPage")
                        .WithMany("Elements")
                        .HasForeignKey("CoverPageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WordGenerator.Api.Domain.Entities.ImageItem", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WordGenerator.Api.Domain.Entities.MasterSection", "MasterSection")
                        .WithMany("Elements")
                        .HasForeignKey("MasterSectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WordGenerator.Api.Domain.Entities.SubSection", "SubSection")
                        .WithMany("Elements")
                        .HasForeignKey("SubSectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WordGenerator.Api.Domain.Entities.DynamicTable", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WordGenerator.Api.Domain.Entities.TemplateSection", "TemplateSection")
                        .WithMany("Elements")
                        .HasForeignKey("TemplateSectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CoverPage");

                    b.Navigation("Image");

                    b.Navigation("MasterSection");

                    b.Navigation("SubSection");

                    b.Navigation("Table");

                    b.Navigation("TemplateSection");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.CoverPageItem", b =>
                {
                    b.HasOne("WordGenerator.Api.Domain.Entities.CoverPageTemplate", "CoverPageTemplate")
                        .WithMany("Items")
                        .HasForeignKey("CoverPageTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoverPageTemplate");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.CoverPageTemplate", b =>
                {
                    b.HasOne("WordGenerator.Api.Domain.Entities.DocumentTemplate", "DocumentTemplate")
                        .WithOne("CoverPage")
                        .HasForeignKey("WordGenerator.Api.Domain.Entities.CoverPageTemplate", "DocumentTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentTemplate");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.DynamicTable", b =>
                {
                    b.HasOne("WordGenerator.Api.Domain.Entities.CoverPageTemplate", "CoverPage")
                        .WithMany()
                        .HasForeignKey("CoverPageTemplateId");

                    b.HasOne("WordGenerator.Api.Domain.Entities.MasterSection", "MasterSection")
                        .WithMany()
                        .HasForeignKey("MasterSectionId");

                    b.HasOne("WordGenerator.Api.Domain.Entities.SubSection", "SubSection")
                        .WithMany()
                        .HasForeignKey("SubSectionId");

                    b.HasOne("WordGenerator.Api.Domain.Entities.TemplateSection", "Section")
                        .WithMany()
                        .HasForeignKey("TemplateSectionId");

                    b.Navigation("CoverPage");

                    b.Navigation("MasterSection");

                    b.Navigation("Section");

                    b.Navigation("SubSection");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.ImageGroup", b =>
                {
                    b.HasOne("WordGenerator.Api.Domain.Entities.CoverPageTemplate", "CoverPage")
                        .WithMany()
                        .HasForeignKey("CoverPageId");

                    b.HasOne("WordGenerator.Api.Domain.Entities.MasterSection", "MasterSection")
                        .WithMany()
                        .HasForeignKey("MasterSectionId");

                    b.HasOne("WordGenerator.Api.Domain.Entities.SubSection", "SubSection")
                        .WithMany()
                        .HasForeignKey("SubSectionId");

                    b.HasOne("WordGenerator.Api.Domain.Entities.TemplateSection", "TemplateSection")
                        .WithMany()
                        .HasForeignKey("TemplateSectionId");

                    b.Navigation("CoverPage");

                    b.Navigation("MasterSection");

                    b.Navigation("SubSection");

                    b.Navigation("TemplateSection");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.ImageItem", b =>
                {
                    b.HasOne("WordGenerator.Api.Domain.Entities.CoverPageTemplate", "CoverPage")
                        .WithMany()
                        .HasForeignKey("CoverPageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WordGenerator.Api.Domain.Entities.ImageGroup", "ImageGroup")
                        .WithMany("Images")
                        .HasForeignKey("ImageGroupId");

                    b.HasOne("WordGenerator.Api.Domain.Entities.MasterSection", "MasterSection")
                        .WithMany()
                        .HasForeignKey("MasterSectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WordGenerator.Api.Domain.Entities.SubSection", "SubSection")
                        .WithMany()
                        .HasForeignKey("SubSectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WordGenerator.Api.Domain.Entities.TemplateSection", "Section")
                        .WithMany()
                        .HasForeignKey("TemplateSectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CoverPage");

                    b.Navigation("ImageGroup");

                    b.Navigation("MasterSection");

                    b.Navigation("Section");

                    b.Navigation("SubSection");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.MasterSection", b =>
                {
                    b.HasOne("WordGenerator.Api.Domain.Entities.DocumentTemplate", "Template")
                        .WithMany("MasterSections")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.SubSection", b =>
                {
                    b.HasOne("WordGenerator.Api.Domain.Entities.MasterSection", "MasterSection")
                        .WithMany("SubSections")
                        .HasForeignKey("MasterSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MasterSection");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.TableColumnDefinition", b =>
                {
                    b.HasOne("WordGenerator.Api.Domain.Entities.DynamicTable", "Table")
                        .WithMany("Columns")
                        .HasForeignKey("DynamicTableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.TableDataCell", b =>
                {
                    b.HasOne("WordGenerator.Api.Domain.Entities.TableColumnDefinition", "Column")
                        .WithMany("Cells")
                        .HasForeignKey("TableColumnDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WordGenerator.Api.Domain.Entities.TableDataRow", "Row")
                        .WithMany("Cells")
                        .HasForeignKey("TableDataRowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Column");

                    b.Navigation("Row");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.TableDataRow", b =>
                {
                    b.HasOne("WordGenerator.Api.Domain.Entities.DynamicTable", "Table")
                        .WithMany("Rows")
                        .HasForeignKey("DynamicTableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.TemplateSection", b =>
                {
                    b.HasOne("WordGenerator.Api.Domain.Entities.DocumentTemplate", "Template")
                        .WithMany("Sections")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.CoverPageTemplate", b =>
                {
                    b.Navigation("Elements");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.DocumentTemplate", b =>
                {
                    b.Navigation("CoverPage");

                    b.Navigation("MasterSections");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.DynamicTable", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("Rows");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.ImageGroup", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.MasterSection", b =>
                {
                    b.Navigation("Elements");

                    b.Navigation("SubSections");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.SubSection", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.TableColumnDefinition", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.TableDataRow", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.TemplateSection", b =>
                {
                    b.Navigation("Elements");
                });
#pragma warning restore 612, 618
        }
    }
}
