// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WordGenerator.Api.Infra.Context;

#nullable disable

namespace WordGenerator.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608211839_FixTableCascadeDelete")]
    partial class FixTableCascadeDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.CoverPageItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CoverPageTemplateId")
                        .HasColumnType("bigint");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CoverPageTemplateId");

                    b.ToTable("CoverPageItems");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.CoverPageTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DocumentTemplateId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTemplateId")
                        .IsUnique();

                    b.ToTable("CoverPageTemplates");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.DocumentTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DocumentTemplates");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.DynamicTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CoverPageTemplateId")
                        .HasColumnType("bigint");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("RowNumberHeader")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ShowRowNumbers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long?>("TemplateSectionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CoverPageTemplateId");

                    b.HasIndex("TemplateSectionId");

                    b.ToTable("DynamicTables", (string)null);
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.SectionParagraph", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<long>("TemplateSectionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TemplateSectionId");

                    b.ToTable("SectionParagraphs");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.TableColumnDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DynamicTableId")
                        .HasColumnType("bigint");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsRowNumberColumn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("DynamicTableId");

                    b.ToTable("TableColumns", (string)null);
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.TableDataCell", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("TableColumnDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<long>("TableDataRowId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("TableColumnDefinitionId");

                    b.HasIndex("TableDataRowId", "TableColumnDefinitionId")
                        .IsUnique();

                    b.ToTable("TableCells", (string)null);
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.TableDataRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DynamicTableId")
                        .HasColumnType("bigint");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DynamicTableId");

                    b.ToTable("TableRows", (string)null);
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.TemplateSection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("TemplateSections");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.CoverPageItem", b =>
                {
                    b.HasOne("WordGenerator.Api.Domain.Entities.CoverPageTemplate", "CoverPageTemplate")
                        .WithMany("Items")
                        .HasForeignKey("CoverPageTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoverPageTemplate");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.CoverPageTemplate", b =>
                {
                    b.HasOne("WordGenerator.Api.Domain.Entities.DocumentTemplate", "DocumentTemplate")
                        .WithOne("CoverPage")
                        .HasForeignKey("WordGenerator.Api.Domain.Entities.CoverPageTemplate", "DocumentTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentTemplate");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.DynamicTable", b =>
                {
                    b.HasOne("WordGenerator.Api.Domain.Entities.CoverPageTemplate", "CoverPage")
                        .WithMany("Tables")
                        .HasForeignKey("CoverPageTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WordGenerator.Api.Domain.Entities.TemplateSection", "Section")
                        .WithMany("Tables")
                        .HasForeignKey("TemplateSectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CoverPage");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.SectionParagraph", b =>
                {
                    b.HasOne("WordGenerator.Api.Domain.Entities.TemplateSection", "Section")
                        .WithMany("Paragraphs")
                        .HasForeignKey("TemplateSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.TableColumnDefinition", b =>
                {
                    b.HasOne("WordGenerator.Api.Domain.Entities.DynamicTable", "Table")
                        .WithMany("Columns")
                        .HasForeignKey("DynamicTableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.TableDataCell", b =>
                {
                    b.HasOne("WordGenerator.Api.Domain.Entities.TableColumnDefinition", "Column")
                        .WithMany("Cells")
                        .HasForeignKey("TableColumnDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WordGenerator.Api.Domain.Entities.TableDataRow", "Row")
                        .WithMany("Cells")
                        .HasForeignKey("TableDataRowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Column");

                    b.Navigation("Row");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.TableDataRow", b =>
                {
                    b.HasOne("WordGenerator.Api.Domain.Entities.DynamicTable", "Table")
                        .WithMany("Rows")
                        .HasForeignKey("DynamicTableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.TemplateSection", b =>
                {
                    b.HasOne("WordGenerator.Api.Domain.Entities.DocumentTemplate", "Template")
                        .WithMany("Sections")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.CoverPageTemplate", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Tables");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.DocumentTemplate", b =>
                {
                    b.Navigation("CoverPage");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.DynamicTable", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("Rows");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.TableColumnDefinition", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.TableDataRow", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.TemplateSection", b =>
                {
                    b.Navigation("Paragraphs");

                    b.Navigation("Tables");
                });
#pragma warning restore 612, 618
        }
    }
}
