// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WordGenerator.Api.Infra.Context;

#nullable disable

namespace WordGenerator.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.CoverPageItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CoverPageTemplateId")
                        .HasColumnType("bigint");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CoverPageTemplateId");

                    b.ToTable("CoverPageItem");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.CoverPageTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DocumentTemplateId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTemplateId")
                        .IsUnique();

                    b.ToTable("CoverPageTemplate");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.DocumentTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DocumentTemplates");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.SectionParagraph", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<long>("TemplateSectionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TemplateSectionId");

                    b.ToTable("SectionParagraph");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.TemplateSection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("TemplateSection");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.CoverPageItem", b =>
                {
                    b.HasOne("WordGenerator.Api.Domain.Entities.CoverPageTemplate", "CoverPageTemplate")
                        .WithMany("Items")
                        .HasForeignKey("CoverPageTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoverPageTemplate");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.CoverPageTemplate", b =>
                {
                    b.HasOne("WordGenerator.Api.Domain.Entities.DocumentTemplate", "DocumentTemplate")
                        .WithOne("CoverPage")
                        .HasForeignKey("WordGenerator.Api.Domain.Entities.CoverPageTemplate", "DocumentTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentTemplate");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.SectionParagraph", b =>
                {
                    b.HasOne("WordGenerator.Api.Domain.Entities.TemplateSection", "Section")
                        .WithMany("Paragraphs")
                        .HasForeignKey("TemplateSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.TemplateSection", b =>
                {
                    b.HasOne("WordGenerator.Api.Domain.Entities.DocumentTemplate", "Template")
                        .WithMany("Sections")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.CoverPageTemplate", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.DocumentTemplate", b =>
                {
                    b.Navigation("CoverPage");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("WordGenerator.Api.Domain.Entities.TemplateSection", b =>
                {
                    b.Navigation("Paragraphs");
                });
#pragma warning restore 612, 618
        }
    }
}
